//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::TMPro.TMP_TextEventHandler.CharacterSelectionEvent))]
	public class PropertyProvider_TMPro_TMP_TextEventHandler_CharacterSelectionEvent : Unity.VisualScripting.SerializedPropertyProvider<TMPro.TMP_TextEventHandler.CharacterSelectionEvent>
	{
	}
}
