//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.XR.CoreUtils.ColorUnityEvent))]
	public class PropertyProvider_Unity_XR_CoreUtils_ColorUnityEvent : Unity.VisualScripting.SerializedPropertyProvider<Unity.XR.CoreUtils.ColorUnityEvent>
	{
	}
}
