//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.Mathematics.bool2x2))]
	public class PropertyProvider_Unity_Mathematics_bool2x2 : Unity.VisualScripting.SerializedPropertyProvider<Unity.Mathematics.bool2x2>
	{
	}
}
