name: TrainAR Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # Build the documentation
  build:
    runs-on: windows-2022 # Pin to VS 2022/MSBuild 17 for DocFX metadata extraction compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      - name: Install DocFX
        run: dotnet tool update --global docfx

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build
        run: $env:USERPROFILE\.dotnet\tools\docfx Documentation/docfx.json

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site # Must equals the 'build.dest' value on your docfx.json

  # Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site

      # List downloaded files
      - name: List downloaded files
        run: ls -la _site

      # Deploy to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          verbose: true
